<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Bundle by: http://www.joomlapro.com.br/ - Bruno Batista</string>
	<key>name</key>
	<string>Joomla3</string>
	<key>scopeName</key>
	<string>source.joomla3</string>
</dict>
</plist>
